In [4]:
import numpy as np 
import pandas as pd 


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/mervebzn/factsale/FactSale.csv

****Initial Exploration****

In [2]:
df= pd.read_csv("/kaggle/input/datasets/mervebzn/factsale/FactSale.csv")
print("Shape (rows,columns):", df.shape)

Shape (rows,columns): (26397, 21)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26397 entries, 0 to 26396
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Sale Key              26397 non-null  int64
 1   City Key              26397 non-null  int64
 2   Customer Key          26397 non-null  int64
 3   Bill To Customer Key  26397 non-null  int64
 4   Stock Item Key        26397 non-null  int64
 5   Invoice Date Key      26397 non-null  object
 6   Delivery Date Key     26384 non-null  object
 7   Salesperson Key       26397 non-null  int64
 8   WWI Invoice ID        26397 non-null  int64
 9   Description           26397 non-null  object
 10  Package               26397 non-null  object
 11  Quantity              26397 non-null  int64
 12  Unit Price            26397 non-null  float64
 13  Tax Rate              26397 non-null  int64
 14  Total Excluding Tax   26397 non-null  float64
 15  Tax Amount            26397 non-null  float64
 16  Profit                26397 non-null  float64
 17  Total Including Tax   26397 non-null  float64
 18  Total Dry Items       26397 non-null  int64
 19  Total Chiller Items   26397 non-null  int64
 20  Lineage Key           26397 non-null  int64
dtypes: float64(5), int64(12), object(4)
memory usage: 4.2+ MB

In [4]:
df.head()

,Sale Key,City Key,Customer Key,Bill To Customer Key,Stock Item Key,Invoice Date Key,Delivery Date Key,Salesperson Key,WWI Invoice ID,Description,...,Quantity,Unit Price,Tax Rate,Total Excluding Tax,Tax Amount,Profit,Total Including Tax,Total Dry Items,Total Chiller Items,Lineage Key
0,49265,41568,0,0,204,10/22/2013,10/23/2013,83,15189,DBA joke mug - mind if I join you? (White),...,6,13.0,15,78.0,11.7,51.0,89.7,6,0,11
1,49372,48937,0,0,173,10/22/2013,10/23/2013,83,15218,Developer joke mug - a foo walks into a bar (B...,...,6,13.0,15,78.0,11.7,51.0,89.7,6,0,11
2,50379,91464,0,0,174,10/28/2013,10/29/2013,70,15525,Developer joke mug - a foo walks into a bar (W...,...,6,13.0,15,78.0,11.7,51.0,89.7,6,0,11
3,51852,48937,0,0,171,11/6/2013,11/7/2013,74,15986,Developer joke mug - this code was generated b...,...,6,13.0,15,78.0,11.7,51.0,89.7,6,0,11
4,52374,89925,0,0,203,11/8/2013,11/9/2013,39,16138,DBA joke mug - mind if I join you? (Black),...,6,13.0,15,78.0,11.7,51.0,89.7,6,0,11

In [5]:
df.describe()

,Sale Key,City Key,Customer Key,Bill To Customer Key,Stock Item Key,Salesperson Key,WWI Invoice ID,Quantity,Unit Price,Tax Rate,Total Excluding Tax,Tax Amount,Profit,Total Including Tax,Total Dry Items,Total Chiller Items,Lineage Key
count,26397.000000,26397.000000,26397.000000,26397.000000,26397.000000,26397.000000,26397.000000,26397.000000,26397.000000,26397.000000,26397.000000,26397.000000,26397.000000,26397.000000,26397.000000,26397.000000,26397.0
mean,113325.365079,72654.379248,111.540781,49.487934,111.130735,101.109785,34929.902262,38.969201,44.775579,14.978028,753.100458,112.720569,375.947710,865.821027,38.425503,0.543698,11.0
std,65852.471369,25386.126544,125.849109,86.398718,63.567575,46.422963,20323.753274,54.119390,135.170950,0.330730,1444.947561,216.671684,762.047362,1661.584982,53.702461,9.313398,0.0
min,2.000000,40550.000000,0.000000,0.000000,1.000000,4.000000,2.000000,1.000000,0.660000,10.000000,3.200000,0.480000,-645.000000,3.680000,0.000000,0.000000,11.0
25%,56575.000000,47673.000000,0.000000,0.000000,56.000000,72.000000,17418.000000,5.000000,13.000000,15.000000,96.000000,14.400000,50.400000,110.400000,5.000000,0.000000,11.0
50%,112395.000000,72709.000000,52.000000,1.000000,111.000000,105.000000,34613.000000,10.000000,18.000000,15.000000,226.800000,34.020000,120.000000,260.820000,9.000000,0.000000,11.0
75%,170972.000000,91372.000000,201.000000,1.000000,167.000000,143.000000,52699.000000,60.000000,32.000000,15.000000,864.000000,129.600000,390.000000,993.600000,60.000000,0.000000,11.0
max,228211.000000,115719.000000,399.000000,202.000000,227.000000,174.000000,70495.000000,360.000000,1899.000000,15.000000,18990.000000,2848.500000,9200.000000,21838.500000,360.000000,240.000000,11.0

In [6]:
# Missing values
df.isna().sum()

Sale Key                 0
City Key                 0
Customer Key             0
Bill To Customer Key     0
Stock Item Key           0
Invoice Date Key         0
Delivery Date Key       13
Salesperson Key          0
WWI Invoice ID           0
Description              0
Package                  0
Quantity                 0
Unit Price               0
Tax Rate                 0
Total Excluding Tax      0
Tax Amount               0
Profit                   0
Total Including Tax      0
Total Dry Items          0
Total Chiller Items      0
Lineage Key              0
dtype: int64

In [7]:
# Duplicated rows
df.duplicated().sum()

np.int64(0)

In [8]:
# Nunique value count per column
df.nunique()

Sale Key                26397
City Key                  153
Customer Key               49
Bill To Customer Key        3
Stock Item Key            227
Invoice Date Key         1064
Delivery Date Key        1063
Salesperson Key            99
WWI Invoice ID           8188
Description               227
Package                     4
Quantity                   61
Unit Price                 62
Tax Rate                    2
Total Excluding Tax       481
Tax Amount                483
Profit                    547
Total Including Tax       486
Total Dry Items            62
Total Chiller Items        15
Lineage Key                 1
dtype: int64

****Data Cleaning****

In [9]:
# Converts dates to datetime
df['Invoice Date Key']  = pd.to_datetime(df['Invoice Date Key'], format='%m/%d/%Y')
df['Delivery Date Key'] = pd.to_datetime(df['Delivery Date Key'], format='%m/%d/%Y')

df[['Invoice Date Key', 'Delivery Date Key']].dtypes

Invoice Date Key     datetime64[ns]
Delivery Date Key    datetime64[ns]
dtype: object

In [10]:
#Missing delivery date
missing_delivery = df[df['Delivery Date Key'].isna()]
missing_delivery[['Sale Key', 'Invoice Date Key', 'Customer Key', 'WWI Invoice ID','Delivery Date Key']]

,Sale Key,Invoice Date Key,Customer Key,WWI Invoice ID,Delivery Date Key
23493,228211,2016-05-31,0,70495,NaT
23585,228210,2016-05-31,0,70495,NaT
23637,228112,2016-05-31,0,70464,NaT
23688,228114,2016-05-31,0,70464,NaT
24111,228111,2016-05-31,0,70464,NaT
24112,228113,2016-05-31,0,70464,NaT
24113,228115,2016-05-31,0,70464,NaT
24746,228069,2016-05-31,109,70454,NaT
24988,228070,2016-05-31,109,70454,NaT
24989,228071,2016-05-31,109,70454,NaT
25540,228200,2016-05-31,375,70491,NaT
26071,228201,2016-05-31,375,70491,NaT
26318,228199,2016-05-31,375,70491,NaT

In [11]:
# 13 sales from the last day in the dataset (2016-05-31) had no delivery date yet —
# most likely because delivery had not occurred by the data extraction date.
print(missing_delivery['Invoice Date Key'].unique())
df['Is Delivered']= df['Invoice Date Key'].notna()

<DatetimeArray>
['2016-05-31 00:00:00']
Length: 1, dtype: datetime64[ns]

In [12]:
zero_cust = df[df['Customer Key'] == 0]
print('Zero customer count:', len(zero_cust))
print('% of total rows: ', len(zero_cust)/ len(df) * 100)

Zero customer count: 9077
% of total rows:  34.38648331249763

In [13]:
zero_cust['Invoice Date Key'].describe()

count                             9077
mean     2014-10-14 10:43:27.293158656
min                2013-01-01 00:00:00
25%                2013-12-23 00:00:00
50%                2014-10-24 00:00:00
75%                2015-08-14 00:00:00
max                2016-05-31 00:00:00
Name: Invoice Date Key, dtype: object

In [14]:
zero_cust['Salesperson Key'].value_counts().head(5)

Salesperson Key
19     857
129    414
119    352
143    321
108    305
Name: count, dtype: int64

In [15]:
print('Zero-key avg Total Excl Tax:', zero_cust['Total Excluding Tax'].mean())
print('Normal avg TOtal Excl Tax:', df[df['Customer Key'] !=0]['Total Excluding Tax'].mean())

Zero-key avg Total Excl Tax: 745.6996474606148
Normal avg TOtal Excl Tax: 756.9790473441109

Not deleted or altered — 0 represents "No registered Customer ID / Retail-Walk-in sale."
 (no transformation applied)

**Data Validation**

In [16]:
print('Product price check:', (round(df['Quantity'] * df['Unit Price'],2) == round(df['Total Excluding Tax'],2)).all())
print('Tax check:',(round(df['Total Excluding Tax'] + df['Tax Amount'],2) == round(df['Total Including Tax'],2)).all())
print('Item count check:',(df['Total Dry Items']+ df['Total Chiller Items'] == df['Quantity']).all())

Product price check: True
Tax check: True
Item count check: True

In [17]:
df['Expected Tax'] = round(df['Total Excluding Tax'] * df['Tax Rate'] / 100, 2)
tax_mismatch = df[round(df['Expected Tax'], 2) != round(df['Tax Amount'], 2)]
print('Which Tax Rate?', tax_mismatch['Tax Rate'].value_counts())
# 253 rows (~1%) show a fixed -0.01 deviation, all at 15% tax rate -> rounding rule difference, not an error

Which Tax Rate? Tax Rate
15    253
Name: count, dtype: int64

In [18]:
# Negative profit investigation
neg_profit = df[df['Profit']<0]
print('Negative profit row count:', len(neg_profit))
print('% of total', len(neg_profit)/len(df) * 100)

Negative profit row count: 566
% of total 2.1441830511042923

In [19]:
mask_count = neg_profit['Description'].value_counts()
print('Halloween mask total', mask_count[mask_count.index.str.contains('Halloween zombie mask')].sum())
print('Share of all negative rows:',mask_count[mask_count.index.str.contains('Halloween zombie mask')].sum()/len(neg_profit)*100)

Halloween mask total 492
Share of all negative rows: 86.92579505300353

In [20]:
mask_all = df[df['Description'].str.contains('Halloween zombie mask', na=False)]
print("\nTotal sales of this product:", len(mask_all))
print("How many are negative profit:", (mask_all['Profit'] < 0).sum())

Total sales of this product: 492
How many are negative profit: 492

In [21]:
mask_all = df[df['Description'].str.contains('Halloween zombie mask', na=False)].copy()
mask_all['Implied Unit Cost'] = mask_all['Unit Price'] - (mask_all['Profit'] / mask_all['Quantity'])

print("Average Unit Price:",mask_all['Unit Price'].mean())
print("Implied Unit Cost:", mask_all['Implied Unit Cost'].mean())

Average Unit Price: 18.0
Implied Unit Cost: 19.0

In [26]:
df['Sold Below Cost'] = df['Profit'] < 0

In [23]:
# Package column consistency
print("\nUnique Package values:", df['Package'].unique())
print("Any leading/trailing spaces?:", (df['Package'] != df['Package'].str.strip()).sum())
print("Case variations?:", (df['Package'] != df['Package'].str.title()).sum())

Unique Package values: ['Each' 'Packet' 'Pair' 'Bag']
Any leading/trailing spaces?: 0
Case variations?: 0

In [24]:
# Final dtype check
print("\nFinal dtypes:")
print(df.dtypes)

Final dtypes:
Sale Key                         int64
City Key                         int64
Customer Key                     int64
Bill To Customer Key             int64
Stock Item Key                   int64
Invoice Date Key        datetime64[ns]
Delivery Date Key       datetime64[ns]
Salesperson Key                  int64
WWI Invoice ID                   int64
Description                     object
Package                         object
Quantity                         int64
Unit Price                     float64
Tax Rate                         int64
Total Excluding Tax            float64
Tax Amount                     float64
Profit                         float64
Total Including Tax            float64
Total Dry Items                  int64
Total Chiller Items              int64
Lineage Key                      int64
Is Delivered                      bool
Expected Tax                   float64
Sold Below Cost                   bool
dtype: object

In [25]:
df.to_csv('cleaned_fact_sale.csv', index=False)
print("Saved:", df.shape)

Saved: (26397, 24)